# fly.toml app configuration file generated for broken-mountain-1855 on 2023-11-07T22:29:24-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "broken-mountain-1855"
primary_region = "sea"

[build]

[env]
  PORT = "3000" 

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
